name: build.yaml
on:
  push:
    branches:
      - main
      - release/**
      - ci

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

  merge_group:

  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Dry-Run'
        default: 'true'
        required: false

permissions:
  contents: write       # for publishing a GitHub release and creating release backpropagation PRs
  issues: write         # for commenting on released issues
  pull-requests: write  # for commenting on released pull requests and creating release backpropagation PRs
  id-token: write       # to enable use of OIDC for trusted publishing and npm provenance

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 24
  DRY_RUN: true

jobs:
  lint-eslint:
    name: Lint / ESLint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-node
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore ESLint cache
        uses: actions/cache/restore@v4
        with:
          path: .cache/eslint
          key: eslint-${{ runner.os }}-${{ hashFiles('package-lock.yaml', 'package.json') }}
          restore-keys: |
            eslint-${{ runner.os }}-

      - name: ESLint
        run: npm run eslint

      - name: Save ESLint cache
        if: github.event_name == 'push'
        uses: actions/cache/save@v4
        with:
          path: .cache/eslint
          key: eslint-${{ runner.os }}-${{ hashFiles('package-lock.yaml', 'package.json') }}-${{ github.run_id }}

  release:
    name: Release
    needs: lint-eslint
    uses: ./.github/workflows/_release.yaml
    with:
      dry_run: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/ci' }}
